### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by essencient** [freshworks/crayons#426]
I suddenly started getting the following error in the console. No idea what is causing it but I think its in the Crayons code.

TypeError: Cannot read properties of undefined (reading 'replace')
    at m.setSVGState (p-evq6zlzw.entry.js:1:460917)
    at m.componentWillLoad (p-evq6zlzw.entry.js:1:460979)
    at Y (p-7a09e628.js:1:7858)
    at I (p-7a09e628.js:1:6041)
    at r (p-7a09e628.js:1:10373)
    at p-7a09e628.js:1:7462
    at Array.map (<anonymous>)
    at J (p-7a09e628.js:1:7455)
    at Array.l (p-7a09e628.js:1:5952)
    at ve (p-7a09e628.js:1:11825)

**Comment by kishore-kumar-E3682** [comment]
@essencient can you provide a code sample or scenario where this error occurs.

**Comment by kishore-kumar-E3682** [comment]
@essencient closing this issue since the chat is inactive.
